# -*- coding: utf-8 -*-
"""ImersãoDadosAlura01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UIwHnFfWdHNK9rZqMqsi7RmdR6HigDo7
"""

import pandas as pd

fonte = "https://github.com/alura-cursos/imersao-dados-2-2020/blob/master/MICRODADOS_ENEM_2019_SAMPLE_43278.csv?raw=true"

dados = pd.read_csv(fonte)
dados.head()

dados.shape

dados["SG_UF_RESIDENCIA"]

dados.columns.values

dados [["SG_UF_RESIDENCIA", "Q025"]]

dados ["SG_UF_RESIDENCIA"].unique()

dados[["NU_IDADE", "SG_UF_RESIDENCIA"]] . hist

dados["NU_IDADE"].value_counts()

dados["NU_IDADE"]. hist()

dados["NU_IDADE"]. hist(bins = 20, figsize = (10, 8))

dados["NU_NOTA_REDACAO"].mean()

dados["NU_NOTA_REDACAO"].std()

"""Desafio 01: Proporção dos inscritos por idade.

Desafio 02: Descobrir de quais estados são os inscritos com 13 anos.

Desafio 03: Adicionar título no gráfico

Desafio 04: Plotar os histogramas das idades dos do treineiros e não treineiros.

Desafio 05: Comparar as distribuições das provas em inglês espanhol

Desafio 06: Explorar as documentações e visualizações
"""

#Desafio 01
dados["NU_IDADE"].value_counts()*100/dados["NU_IDADE"].count()

#Desafio 02
dados.query("NU_IDADE==13")["SG_UF_RESIDENCIA"].value_counts()

#Desafio 03
idade = dados["NU_IDADE"]
porc_idade = ((idade.value_counts(normalize=True).sort_index())*100)
porc_idade.plot.bar(figsize = (15, 10), color=["black", "pink"], title = "Idade dos inscritos - ENEM 2019")

#Desafio 04
import matplotlib.pyplot as plt

treineiros = dados.query("IN_TREINEIRO == 1")
n_treineiros = dados.query("IN_TREINEIRO == 0")

idade_treineiros = treineiros["NU_IDADE"].value_counts()
idade_n_treineiros = n_treineiros["NU_IDADE"].value_counts()

plt.figure(figsize=[10,5])
plt.hist([idade_treineiros, idade_n_treineiros])
plt.legend(["Treineiros", "Não treineiros"])
plt.show()

#Desafio 5
ingles = dados.query("TP_LINGUA ==0")["NU_NOTA_LC"].value_counts()
espanhol = dados.query("TP_LINGUA ==1")["NU_NOTA_LC"].value_counts()

plt.boxplot([ingles, espanhol])
plt.title("Boxplot Inglês & Espanhol")

#Desafio 6